---
driver:
  name: docker

provisioner:
  name: ansible_playbook
  hosts: test-kitchen
  require_chef_for_busser: false
  require_ansible_omnibus: false
  require_ansible_repo: false
  ansible_version: 2.5.6.0
  ansible_verbose: false
  ansible_verbosity: 2
  ansible_extra_flags: <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>
  ignore_paths_from_root:
    - .kitchen

platforms:
  - name: ubuntu-16.04
    driver_config:
      image: solita/ubuntu-systemd
      platform: ubuntu
      privileged: true
      run_command: /sbin/init
      provision_command:
        - apt-get update
        - apt-get install -y iproute git python-pip curl
        - pip install ansible pyopenssl
  - name: centos-7.2
    driver_config:
      image: centos/systemd
      platform: centos
      privileged: true
      run_command: /sbin/init
      provision_command:
        - yum install -y iproute tuned epel-release ansible
        # https://github.com/CentOS/CentOS-Dockerfiles/issues/173
        - systemctl enable systemd-user-sessions.service && ln -s /usr/lib/systemd/system/systemd-user-sessions.service /etc/systemd/system/default.target.wants/systemd-user-sessions.service

verifier:
  name: serverspec
  default_pattern: true

suites:
  - name: server01
    driver_config:
      hostname: server01.internal
      publish_all: true
      instance_name: server01
      run_options:
        network: consul-net
        ip: 172.250.48.1
  - name: server02
    driver_config:
      hostname: server02.internal
      publish_all: true
      instance_name: server02
      run_options:
        network: consul-net
        ip: 172.250.48.2
  - name: server03
    driver_config:
      hostname: server03.internal
      publish_all: true
      instance_name: server03
      run_options:
        network: consul-net
        ip: 172.250.48.3
  - name: client
    driver_config:
      hostname: client.internal
      publish_all: true
      instance_name: client
      run_options:
        network: consul-net
        ip: 172.250.48.4

lifecycle:
  pre_create:
    - docker network create consul-net --subnet=172.250.48.0/16 || true
