#https://www.consul.io/docs/install/ports.html

- name: Check firewalld configuration
  shell: firewall-cmd --list-ports
  register: firewall_result

- name: open port 8500 tcp
  firewalld:
    port: 8500/tcp
    permanent: yes
    immediate: yes
    state: enabled
  when: "'8500/tcp' not in firewall_result.stdout"

- name: open port 8600 tcp
  firewalld:
    port: 8600/tcp
    permanent: yes
    immediate: yes
    state: enabled
  when: "'8600/tcp' not in firewall_result.stdout"

- name: open port 8600 udp
  firewalld:
    port: 8600/udp
    permanent: yes
    immediate: yes
    state: enabled
  when: "'8600/udp' not in firewall_result.stdout"

- name: open port 8300 tcp
  firewalld:
    port: 8300/tcp
    permanent: yes
    immediate: yes
    state: enabled
  when: "'8300/tcp' not in firewall_result.stdout"

- name: open port 8301 tcp
  firewalld:
    port: 8301/tcp
    permanent: yes
    immediate: yes
    state: enabled
  when: "'8301/tcp' not in firewall_result.stdout"

- name: open port 8302 tcp
  firewalld:
    port: 8302/tcp
    permanent: yes
    immediate: yes
    state: enabled
  when: "'8302/tcp' not in firewall_result.stdout"

- name: open port 8301 udp
  firewalld:
    port: 8301/udp
    permanent: yes
    immediate: yes
    state: enabled
  when: "'8301/udp' not in firewall_result.stdout"

- name: open port 8302 udp
  firewalld:
    port: 8302/udp
    permanent: yes
    immediate: yes
    state: enabled
  when: "'8302/udp' not in firewall_result.stdout"